version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: sports_inventory_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sports_inventory
      MYSQL_USER: sports
      MYSQL_PASSWORD: sports
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: sports_inventory_app
    depends_on:
      - db
    environment:
      SECRET_KEY: "super_secret_key_change_me"
      DB_HOST: "db"
      DB_USER: "sports"
      DB_PASSWORD: "sports"
      DB_NAME: "sports_inventory"
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: flask run --host=0.0.0.0 --port=8080

volumes:
  db_data:
