"""Add ID card code and two-factor authentication

Revision ID: 3584dccc1cf0
Revises: 
Create Date: 2025-06-09 22:23:59.809454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3584dccc1cf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_card_code', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('two_factor_enabled', sa.Boolean(), nullable=True))
        batch_op.create_unique_constraint(None, ['id_card_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('two_factor_enabled')
        batch_op.drop_column('id_card_code')

    # ### end Alembic commands ###
